### ISSUE TITLE
Does the mask input in InjectNoise really work like it says in the README?

### ISSUE THREAD

**Issue by suede299** [BlenderNeko/ComfyUI_Noise#16]
![image](https://github.com/BlenderNeko/ComfyUI_Noise/assets/85022330/47bdc695-2dd5-40b6-afe6-c8568fcc2881)
Injecting noise isn't just injecting ah into the mask region as stated. 
Here are the results I obtained with a simple node:
![image](https://github.com/BlenderNeko/ComfyUI_Noise/assets/85022330/c3f26187-0e0e-43b6-8fe7-617ad276da44)
Or am I misunderstanding, the mask input in bnk's InjectNoise node doesn't function like that.

**Comment by BlenderNeko** [comment]
it only specifies where to inject noise, it doesn't do things like setting the latent noise mask. What happend in your example above is that it did inject noise where you specified, but the sampler tried to denoise the entire image including areas where no noise was present.
![image](https://github.com/BlenderNeko/ComfyUI_Noise/assets/126974546/fc134f48-6fb9-4dc4-8cbf-180575a0b233)
