### ISSUE TITLE
Unsampler with sigmas instead of steps

### ISSUE THREAD

**Issue by SirVeggie** [BlenderNeko/ComfyUI_Noise#40]
Using sigmas instead of steps and end_at_step can achieve much more accurate control over the unsampling. I would like to request a version of the unsampler where you can input sigmas instead. Being even more customizable would be nice too, like SamplerCustomAdvanced, but at least being able to input sigmas would be helpful.

**Comment by SirVeggie** [comment]
I realized this can be done with SamplerCustomAdvanced already, so I'm closing this issue.

**Comment by Latentnaut** [comment]
Hello, I'm having issues to run this Workflow. I'd like to know if you are able to make it work with Flux, and if you could share the Json file over here.

Thank you!
