### ISSUE TITLE
Recent ComfyUi change broke Unsampler node

### ISSUE THREAD

**Issue by InB4DevOps** [BlenderNeko/ComfyUI_Noise#9]
Hey there, 

this change to samply.py broke the Unsampler node: 
https://github.com/comfyanonymous/ComfyUI/commit/036f88c62166a750ecfc88175d2f6836c5707e3b#diff-2e28093f5c1fe698e3f531ad59f86e68cb6947e7c94f9ce142d2ae6ce0fd7506R44

We now need to call convert_cond(positive) / convert_cond(negative) here:

https://github.com/BlenderNeko/ComfyUI_Noise/blob/master/nodes.py#L221

**Comment by InB4DevOps** [comment]
Are you joking? 

> We now need to call convert_cond(positive) / convert_cond(negative) here:
> 
> https://github.com/BlenderNeko/ComfyUI_Noise/blob/master/nodes.py#L221

**Comment by BlenderNeko** [comment]
fixed in latest commit
